import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import tseslint from "typescript-eslint";
import betterTailwind from "eslint-plugin-better-tailwindcss";
import local from "./lint-rules/index.mjs";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // Repo-local rules enforcing the perf / streaming patterns documented in the
  // plan at .claude/plans/when-i-am-harmonic-rainbow.md. Each rule has docs in
  // the header of its file under lint-rules/. Together they prevent regressions
  // of the parallelization (1D), thin-layout (1B), useOptimistic (2C), and
  // lazy-heavy-module (2B) patterns.
  {
    files: ["src/**/*.{ts,tsx,mts,cts}"],
    plugins: { local },
    rules: {
      "local/no-sequential-db-await": "error",
      "local/no-await-in-layout": "error",
      "local/no-router-refresh": "error",
      "local/no-eager-heavy-import": "error",
      // Font-size standardization. Paired with `scripts/check-css-font-size.mjs`
      // (raw CSS) so every surface a font-size can hide on is covered.
      "local/no-inline-font-size": "error",
      "local/no-default-text-size": "error",
      // Colour-system enforcement (see plan
      // .claude/plans/i-want-to-moonlit-sutherland.md). Bans raw CSS colour
      // literals everywhere except the 4 allow-listed colour-authority files.
      // No per-line escape on purpose — pairs with the branded `OklchColor`
      // type so neither plain strings nor literals can sneak into inline styles.
      "local/no-raw-colors": "error",
    },
  },

  // Heavy, type-aware TypeScript rules for our own source.
  // Requires full type information (projectService) so rules like
  // no-floating-promises / no-misused-promises / no-unsafe-* can run.
  {
    files: ["**/*.{ts,tsx,mts,cts}"],
    extends: [
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Force `import type { ... }` so type-only imports never ship to runtime.
      "@typescript-eslint/consistent-type-imports": "error",
      // Allow intentionally-unused identifiers when prefixed with `_`.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },

  // Tailwind: enforce the design-token system and ban drift.
  // `entryPoint` lets the plugin read our globals.css to know which
  // classes/tokens are actually registered.
  {
    files: ["**/*.{ts,tsx,jsx}"],
    plugins: { "better-tailwindcss": betterTailwind },
    settings: {
      "better-tailwindcss": { entryPoint: "src/app/globals.css" },
    },
    rules: {
      "better-tailwindcss/no-unknown-classes": "error",
      "better-tailwindcss/no-conflicting-classes": "error",
      "better-tailwindcss/no-duplicate-classes": "error",
      "better-tailwindcss/no-deprecated-classes": "error",
      // The core adherence rule: no arbitrary values like `p-[13px]` or
      // `bg-[#abc123]`. Define a semantic token in globals.css instead.
      "better-tailwindcss/no-restricted-classes": [
        "error",
        {
          restrict: [
            {
              pattern: "\\[.*\\]",
              message:
                "Arbitrary Tailwind values are banned. Add a semantic token in src/app/globals.css (@theme) and use that class instead.",
            },
          ],
        },
      ],
    },
  },

  // shadcn/ui primitives are vendored, trusted code: they legitimately use
  // arbitrary variants ([&_svg], data-[state=...]) and registry utility names.
  // Keep type-aware TS rules on, but exempt them from the Tailwind drift rules
  // (these components get regenerated by the shadcn CLI, so we don't hand-edit).
  {
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      "better-tailwindcss/no-restricted-classes": "off",
      "better-tailwindcss/no-unknown-classes": "off",
      "better-tailwindcss/no-conflicting-classes": "off",
      // shadcn primitives ship with default Tailwind text-sm / text-xs in
      // their base styles. Don't fight the registry.
      "local/no-default-text-size": "off",
      // shadcn primitives may ship with raw `rgb()` / `rgba()` strings in
      // their generated styles (e.g. animation shadows, focus rings); we
      // override them via `className=` overrides where it matters.
      "local/no-raw-colors": "off",
    },
  },

  // Supabase Edge Functions run on Deno, not Node. They live under their own
  // tsconfig (supabase/functions/tsconfig.json) with a `deno.d.ts` shim for
  // the `Deno` global and URL-import wildcards — that lets the type-aware
  // ESLint rules (no-floating-promises, no-unsafe-*) still run on them
  // without the root projectService throwing "file not found".
  {
    files: ["supabase/functions/**/*.ts"],
    languageOptions: {
      parserOptions: {
        projectService: false,
        project: "./supabase/functions/tsconfig.json",
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // The function code is hand-written for Deno; the local rule set
      // assumes src/** Next.js patterns and doesn't apply here.
      "local/no-sequential-db-await": "off",
      "local/no-await-in-layout": "off",
      "local/no-router-refresh": "off",
      "local/no-eager-heavy-import": "off",
      "local/no-inline-font-size": "off",
      "local/no-default-text-size": "off",
      "local/no-raw-colors": "off",
    },
  },

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run gen:types`; don't lint generated artifacts.
    "src/lib/supabase/database.types.ts",
  ]),
]);

export default eslintConfig;
